# Generated by Django 3.0 on 2022-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=150)),
                ('eage', models.IntegerField(default=20)),
                ('eexp', models.CharField(choices=[('0', 'Select Experience Year'), ('1', 'Year'), ('2', '2 Years'), ('3', '3 Years')], default='0', max_length=10)),
            ],
        ),
    ]
